sudo: required
dist: trusty
language: java

matrix:
  include:
  - jdk: openjdk6
    env: BUILD=MVN

  - jdk: oraclejdk7
    env: BUILD=MVN

  - jdk: oraclejdk8
    env: BUILD=BAZEL

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update

# install:
#   - sudo apt-get install bazel

script:
  # - bazel test ...
  - mvn package
