sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update

install:
  - protoc --version || echo "no protoc"
  - sudo apt-get install bazel
  - protoc --version || echo "no protoc"
  - sudo apt-get install protoc
  - protoc --version || echo "no protoc"

script:
  - protoc --version || echo "no protoc"
  - bazel test ...
