sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update

install:
  - protoc --version || echo "no protoc"
  - sudo apt-get install bazel
  - protoc --version || echo "no protoc"
  - curl -o protoc.zip https://github.com/google/protobuf/releases/download/v3.0.2/protoc-3.0.2-linux-x86_64.zip
  - unzip protoc.zip
  - export PATH=`pwd`/bin/:$PATH
  # - sudo apt-get install protobuf-compiler
  - protoc --version || echo "no protoc"

script:
  - protoc --version || echo "no protoc"
  - bazel test ...
